spring:
  kafka:
    bootstrap-servers: 192.168.111.128:9092
#    template:
#      default-topic: test-event
#    producer:
#      key-serializer:
#  elasticsearch:
#    username:
#    password:

logging:
  level:
    root: info
